#!/usr/bin/env bash
declare -r DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

start() {
    cd ${DIR}
    docker pull debian
    docker pull pihole/pihole
    docker-compose rm
    docker rmi pihole_cloudflared
    docker image prune --force
    docker-compose up --build --detach
}

stop() {
    cd ${DIR}
    docker-compose down
}

case $1 in
    start) start;;
    stop) stop;;
    "") start;;
    *) echo "Usage: ./service start|stop"
esac
